
FROM maven:3.8.3-openjdk-17 AS build

WORKDIR /usr/src/app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn package -DskipTests

FROM openjdk:17

WORKDIR /app

COPY --from=build /usr/src/app/target/BlowFish_In_SB-0.0.1-SNAPSHOT.jar ./app.jar

#
#RUN apk add --no-cache tzdata && \
#    ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && \
#    echo "Asia/Kolkata" > /etc/timezone

#expose the port which is used to run project on local
EXPOSE 9090

CMD ["java","-Dspring.profiles.active=dev", "-jar","app.jar"]