server:
  port: 9090
spring:
  datasource:
    #    url: jdbc:postgresql://10.226.80.20:5446/aiims_delhi
    #    username: aiimsdelhi
    #    password: A11msdelhi@29
    url: jdbc:postgresql://172.17.0.2/
    database: postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 1
      connection-timeout: 30000 #30 Seconds
      idle-timeout: 60000  #1 Minute
      max-lifetime: 240000  #4 Minute
      keepalive-time: 90000 #1 Minute 30 Seconds
      initialization-fail-timeout: 45000  #45 Seconds
      pool-name: Hikari-Pool-Name
      leak-detection-threshold: 2000
    jpa:
      show-sql: ture
      hibernate:
        ddl-auto: none
      open-in-view: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          jdbc:
            batchSize: 100
            orderInserts: true
            orderUpdates: true

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    # 1h in millisecond
    #    expiration-time: 3600000
    # 30Min in millisecond
    #    expiration-time: 1800000
    # 1Min in millisecond
    expiration-time: 60000
