server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://10.226.80.20:5446/aiims_delhi
    username: aiimsdelhi
    password: A11msdelhi@29
  jpa:
    hibernate:
      ddl-auto: none
  open-in-view: false
    show-sql:trues

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    # 1h in millisecond
    #    expiration-time: 3600000
    # 30Min in millisecond
#    expiration-time: 1800000
    # 1Min in millisecond
    expiration-time: 60000
