#server:
#  port: 8005
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/login_system
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#  open-in-view: false
#
#security:
#  jwt:
#    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
#    expiration-time: 3600000

spring:
  application:
    name: spring-security-with-JWT-token
  profiles:
    active: dev

app:
  jwt:
  cors:
    allowed-origins: http://localhost:3000

logging:
  level:
    org.springframework.security: DEBUG