server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login_system
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  open-in-view: false

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    # 1h in millisecond
    #     expiration-time: 3600000
    # 30Min in millisecond
    expiration-time: 1800000